# -*- coding: utf-8 -*-
"""
Generic instrument and sheet information.
"""

from writeLines import write_output_lines

def print_FileHeader(fileID, songName):
    write_output_lines(fileID,'<?xml version="1.0" encoding="UTF-8"?>\n')
    write_output_lines(fileID,'<!DOCTYPE score-partwise PUBLIC "-//Recordare//DTD MusicXML 3.1 Partwise//EN" "http://www.musicxml.org/dtds/partwise.dtd">\n')
    write_output_lines(fileID,'<score-partwise version="3.1">\n')
    write_output_lines(fileID,'  <work>\n')
    write_output_lines(fileID,'    <work-title>%s</work-title>\n'%songName)
    write_output_lines(fileID,'    </work>\n')
    write_output_lines(fileID,'  <identification>\n')
    write_output_lines(fileID,'    <creator type="composer">Composer</creator>\n')
    write_output_lines(fileID,'    <rights>Copyright Owner</rights>\n')
    write_output_lines(fileID,'    <encoding>\n')
    write_output_lines(fileID,'      <software>MuseScore 2.3.2</software>\n')
    write_output_lines(fileID,'      <encoding-date>2021-02-13</encoding-date>\n')
    write_output_lines(fileID,'      <supports element="accidental" type="yes"/>\n')
    write_output_lines(fileID,'      <supports element="beam" type="yes"/>\n')
    write_output_lines(fileID,'      <supports element="print" attribute="new-page" type="yes" value="yes"/>\n')
    write_output_lines(fileID,'      <supports element="print" attribute="new-system" type="yes" value="yes"/>\n')
    write_output_lines(fileID,'      <supports element="stem" type="yes"/>\n')
    write_output_lines(fileID,'      </encoding>\n')
    write_output_lines(fileID,'    </identification>\n')
    write_output_lines(fileID,'  <defaults>\n')
    write_output_lines(fileID,'    <scaling>\n')
    write_output_lines(fileID,'      <millimeters>7.05556</millimeters>\n')
    write_output_lines(fileID,'      <tenths>40</tenths>\n')
    write_output_lines(fileID,'      </scaling>\n')
    write_output_lines(fileID,'    <page-layout>\n')
    write_output_lines(fileID,'      <page-height>1683.36</page-height>\n')
    write_output_lines(fileID,'      <page-width>1190.88</page-width>\n')
    write_output_lines(fileID,'      <page-margins type="even">\n')
    write_output_lines(fileID,'        <left-margin>56.6929</left-margin>\n')
    write_output_lines(fileID,'        <right-margin>56.6929</right-margin>\n')
    write_output_lines(fileID,'        <top-margin>56.6929</top-margin>\n')
    write_output_lines(fileID,'        <bottom-margin>113.386</bottom-margin>\n')
    write_output_lines(fileID,'        </page-margins>\n')
    write_output_lines(fileID,'      <page-margins type="odd">\n')
    write_output_lines(fileID,'        <left-margin>56.6929</left-margin>\n')
    write_output_lines(fileID,'        <right-margin>56.6929</right-margin>\n')
    write_output_lines(fileID,'        <top-margin>56.6929</top-margin>\n')
    write_output_lines(fileID,'        <bottom-margin>113.386</bottom-margin>\n')
    write_output_lines(fileID,'        </page-margins>\n')
    write_output_lines(fileID,'      </page-layout>\n')
    write_output_lines(fileID,'    <word-font font-family="FreeSerif" font-size="10"/>\n')
    write_output_lines(fileID,'    <lyric-font font-family="FreeSerif" font-size="11"/>\n')
    write_output_lines(fileID,'    </defaults>\n')
    write_output_lines(fileID,'  <credit page="1">\n')
    write_output_lines(fileID,'    <credit-words default-x="595.44" default-y="1626.67" justify="center" valign="top" font-size="24">%s</credit-words>\n'%songName)
    write_output_lines(fileID,'    </credit>\n')
    write_output_lines(fileID,'  <credit page="1">\n')
    write_output_lines(fileID,'    <credit-words default-x="595.44" default-y="1569.97" justify="center" valign="top" font-size="14">Subtitle</credit-words>\n')
    write_output_lines(fileID,'    </credit>\n')
    write_output_lines(fileID,'  <credit page="1">\n')
    write_output_lines(fileID,'    <credit-words default-x="1134.19" default-y="1526.67" justify="right" valign="bottom" font-size="12">Composer</credit-words>\n')
    write_output_lines(fileID,'    </credit>\n')
    write_output_lines(fileID,'  <credit page="1">\n')
    write_output_lines(fileID,'    <credit-words default-x="595.44" default-y="113.386" justify="center" valign="bottom" font-size="8">Copyright Owner</credit-words>\n')
    write_output_lines(fileID,'    </credit>\n')
    write_output_lines(fileID,"  <part-list>\n")
    write_output_lines(fileID,'    <score-part id="P1">\n')
    write_output_lines(fileID,'      <part-name print-object="no">Piano</part-name>\n')
    write_output_lines(fileID,'      <score-instrument id="P1-I1">\n')
    write_output_lines(fileID,'        <instrument-name>Piano</instrument-name>\n')
    write_output_lines(fileID,'        </score-instrument>\n')
    write_output_lines(fileID,'      <midi-device id="P1-I1" port="1"></midi-device>\n')
    write_output_lines(fileID,'      <midi-instrument id="P1-I1">\n')
    write_output_lines(fileID,'        <midi-channel>1</midi-channel>\n')
    write_output_lines(fileID,'        <midi-program>1</midi-program>\n')
    write_output_lines(fileID,'        <volume>78.7402</volume>\n')
    write_output_lines(fileID,'        <pan>0</pan>\n')
    write_output_lines(fileID,'        </midi-instrument>\n')
    write_output_lines(fileID,'      </score-part>\n')
    write_output_lines(fileID,'    <score-part id="P2">\n')
    write_output_lines(fileID,'      <part-name print-object="no">Piano</part-name>\n')
    write_output_lines(fileID,'      <score-instrument id="P2-I1">\n')
    write_output_lines(fileID,'        <instrument-name>Piano</instrument-name>\n')
    write_output_lines(fileID,'        </score-instrument>\n')
    write_output_lines(fileID,'      <midi-device id="P2-I1" port="1"></midi-device>\n')
    write_output_lines(fileID,'      <midi-instrument id="P2-I1">\n')
    write_output_lines(fileID,'        <midi-channel>2</midi-channel>\n')
    write_output_lines(fileID,'        <midi-program>1</midi-program>\n')
    write_output_lines(fileID,'        <volume>78.7402</volume>\n')
    write_output_lines(fileID,'        <pan>0</pan>\n')
    write_output_lines(fileID,'        </midi-instrument>\n')
    write_output_lines(fileID,'      </score-part>\n')
    write_output_lines(fileID,'    <score-part id="P3">\n')
    write_output_lines(fileID,'      <part-name print-object="no">Piano</part-name>\n')
    write_output_lines(fileID,'      <score-instrument id="P3-I1">\n')
    write_output_lines(fileID,'        <instrument-name>Piano</instrument-name>\n')
    write_output_lines(fileID,'        </score-instrument>\n')
    write_output_lines(fileID,'      <midi-device id="P3-I1" port="1"></midi-device>\n')
    write_output_lines(fileID,'      <midi-instrument id="P3-I1">\n')
    write_output_lines(fileID,'        <midi-channel>3</midi-channel>\n')
    write_output_lines(fileID,'        <midi-program>1</midi-program>\n')
    write_output_lines(fileID,'        <volume>78.7402</volume>\n')
    write_output_lines(fileID,'        <pan>0</pan>\n')
    write_output_lines(fileID,'        </midi-instrument>\n')
    write_output_lines(fileID,'      </score-part>\n')
    write_output_lines(fileID,'    </part-list>\n')
    
    
def print_part1Intro(fileID,tempo):
    write_output_lines(fileID,'  <part id="P1">\n')
    write_output_lines(fileID,'    <measure number="1" width="338.94">\n')
    write_output_lines(fileID,'      <print>\n')
    write_output_lines(fileID,'        <system-layout>\n')
    write_output_lines(fileID,'          <system-margins>\n')
    write_output_lines(fileID,'            <left-margin>-0.00</left-margin>\n')
    write_output_lines(fileID,'            <right-margin>0.00</right-margin>\n')
    write_output_lines(fileID,'            </system-margins>\n')
    write_output_lines(fileID,'          <top-system-distance>170.00</top-system-distance>\n')
    write_output_lines(fileID,'          </system-layout>\n')
    write_output_lines(fileID,'        </print>\n')
    write_output_lines(fileID,'      <attributes>\n')
    write_output_lines(fileID,'        <divisions>4</divisions>\n')
    write_output_lines(fileID,'        <key>\n')
    write_output_lines(fileID,'          <fifths>0</fifths>\n')
    write_output_lines(fileID,'          </key>\n')
    write_output_lines(fileID,'        <time>\n')
    write_output_lines(fileID,'          <beats>4</beats>\n')
    write_output_lines(fileID,'          <beat-type>4</beat-type>\n')
    write_output_lines(fileID,'          </time>\n')
    write_output_lines(fileID,'        <clef>\n')
    write_output_lines(fileID,'          <sign>G</sign>\n')
    write_output_lines(fileID,'          <line>2</line>\n')
    write_output_lines(fileID,'          </clef>\n')
    write_output_lines(fileID,'        </attributes>\n')
    write_output_lines(fileID,'      <direction placement="above">\n')
    write_output_lines(fileID,'        <direction-type>\n')
    write_output_lines(fileID,'          <metronome parentheses="no" default-x="-33.50" default-y="40.00">\n')
    write_output_lines(fileID,'            <beat-unit>quarter</beat-unit>\n')
    write_output_lines(fileID,'            <per-minute>%d</per-minute>\n'%tempo)
    write_output_lines(fileID,'            </metronome>\n')
    write_output_lines(fileID,'          </direction-type>\n')
    write_output_lines(fileID,'        <sound tempo="%d"/>\n'%tempo)
    write_output_lines(fileID,'        </direction>\n')
    
    
def print_partIntro(fileID,part_name):
    write_output_lines(fileID,'    </part>\n') # end previous part
    write_output_lines(fileID,'  <part id="%s">\n'%part_name)
    write_output_lines(fileID,'    <measure number="1" width="338.94">\n')
    write_output_lines(fileID,'      <print>\n')
    write_output_lines(fileID,'        <staff-layout number="1">\n')
    write_output_lines(fileID,'          <staff-distance>65.00</staff-distance>\n')
    write_output_lines(fileID,'          </staff-layout>\n')
    write_output_lines(fileID,'        </print>\n')
    write_output_lines(fileID,'      <attributes>\n')
    write_output_lines(fileID,'        <divisions>4</divisions>\n')
    write_output_lines(fileID,'        <key>\n')
    write_output_lines(fileID,'          <fifths>0</fifths>\n')
    write_output_lines(fileID,'          </key>\n')
    write_output_lines(fileID,'        <time>\n')
    write_output_lines(fileID,'          <beats>4</beats>\n')
    write_output_lines(fileID,'          <beat-type>4</beat-type>\n')
    write_output_lines(fileID,'          </time>\n')
    write_output_lines(fileID,'        <clef>\n')
    write_output_lines(fileID,'          <sign>G</sign>\n')
    write_output_lines(fileID,'          <line>2</line>\n')
    write_output_lines(fileID,'          </clef>\n')
    write_output_lines(fileID,'        </attributes>\n')
    
    
def print_endxml(fileID):
    write_output_lines(fileID,'    </part>\n')
    write_output_lines(fileID,'  </score-partwise>\n')